import './globals.css'
import 'react-toastify/ReactToastify.min.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import { ThemeProvider } from '@/components/theme-provider'
import { AuthProvider } from './profile/ProfileContext'

const roboto = Roboto({ subsets: ['latin'], weight: "300" })

export const metadata: Metadata = {
  title: 'ImageLite App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={roboto.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider> {/* Adicione o AuthProvider aqui */}
            {children}
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}